<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AddressesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('addresses')->insert([
            ['street_name'=>'Sobieskiego Jana III','building_number'=>12,'postal_code'=>'05-441','city_id'=>9],
            ['street_name'=>'Dworska','building_number'=>83,'postal_code'=>'13-019','city_id'=>245],
            ['street_name'=>'Żwirki Franciszka i Wigury Stanisława','building_number'=>82,'postal_code'=>'72-056','city_id'=>270],
            ['street_name'=>'Reymonta Władysława Stanisława','building_number'=>7,'postal_code'=>'22-656','city_id'=>150],
            ['street_name'=>'Topolowa','building_number'=>66,'postal_code'=>'43-102','city_id'=>6],
            ['street_name'=>'Cegielniana','building_number'=>25,'postal_code'=>'81-131','city_id'=>42],
            ['street_name'=>'Handlowa','building_number'=>13,'postal_code'=>'72-500','city_id'=>301],
            ['street_name'=>'Limanowskiego Bolesława','building_number'=>42,'postal_code'=>'07-910','city_id'=>209],
            ['street_name'=>'Stroma','building_number'=>83,'postal_code'=>'29-716','city_id'=>133],
            ['street_name'=>'Pola Wincentego','building_number'=>78,'postal_code'=>'81-757','city_id'=>177],
            ['street_name'=>'Zamenhofa Ludwika','building_number'=>33,'postal_code'=>'81-884','city_id'=>71],
            ['street_name'=>'Ciasna','building_number'=>69,'postal_code'=>'95-420','city_id'=>314],
            ['street_name'=>'Wileńska','building_number'=>2,'postal_code'=>'99-890','city_id'=>173],
            ['street_name'=>'Urocza','building_number'=>11,'postal_code'=>'22-141','city_id'=>139],
            ['street_name'=>'Jaworowa','building_number'=>99,'postal_code'=>'31-022','city_id'=>219],
            ['street_name'=>'Asnyka Adama','building_number'=>36,'postal_code'=>'71-697','city_id'=>135],
            ['street_name'=>'Kleeberga Franciszka','building_number'=>43,'postal_code'=>'05-593','city_id'=>56],
            ['street_name'=>'Wczasowa','building_number'=>31,'postal_code'=>'84-284','city_id'=>271],
            ['street_name'=>'Sandomierska','building_number'=>47,'postal_code'=>'65-959','city_id'=>241],
            ['street_name'=>'Sportowa','building_number'=>83,'postal_code'=>'40-190','city_id'=>176],
            ['street_name'=>'Niepodległości','building_number'=>56,'postal_code'=>'67-335','city_id'=>93],
            ['street_name'=>'Zbożowa','building_number'=>2,'postal_code'=>'79-218','city_id'=>67],
            ['street_name'=>'Sikorskiego Władysława','building_number'=>97,'postal_code'=>'25-011','city_id'=>217],
            ['street_name'=>'Młynarska','building_number'=>96,'postal_code'=>'40-718','city_id'=>211],
            ['street_name'=>'Parkowa','building_number'=>26,'postal_code'=>'93-319','city_id'=>235],
            ['street_name'=>'Stawowa','building_number'=>34,'postal_code'=>'35-292','city_id'=>294],
            ['street_name'=>'Główna','building_number'=>95,'postal_code'=>'52-161','city_id'=>297],
            ['street_name'=>'Sikorskiego Władysława','building_number'=>76,'postal_code'=>'72-309','city_id'=>68],
            ['street_name'=>'Wandy','building_number'=>51,'postal_code'=>'62-080','city_id'=>30],
            ['street_name'=>'Skargi Piotra','building_number'=>22,'postal_code'=>'64-299','city_id'=>85],
            ['street_name'=>'Szczęśliwa','building_number'=>43,'postal_code'=>'68-550','city_id'=>321],
            ['street_name'=>'Jasna','building_number'=>62,'postal_code'=>'35-621','city_id'=>164],
            ['street_name'=>'Popiełuszki Jerzego','building_number'=>65,'postal_code'=>'50-325','city_id'=>7],
            ['street_name'=>'Srebrna','building_number'=>45,'postal_code'=>'09-110','city_id'=>307],
            ['street_name'=>'Saperów','building_number'=>24,'postal_code'=>'09-510','city_id'=>253],
            ['street_name'=>'Bolesława Krzywoustego','building_number'=>64,'postal_code'=>'85-227','city_id'=>323],
            ['street_name'=>'Piaskowa','building_number'=>70,'postal_code'=>'06-033','city_id'=>27],
            ['street_name'=>'Sokola','building_number'=>27,'postal_code'=>'97-188','city_id'=>214],
            ['street_name'=>'Curie-Skłodowskiej Marii','building_number'=>41,'postal_code'=>'10-811','city_id'=>193],
            ['street_name'=>'Harcerska','building_number'=>2,'postal_code'=>'29-057','city_id'=>104],
            ['street_name'=>'Kasztanowa','building_number'=>12,'postal_code'=>'53-367','city_id'=>180],
            ['street_name'=>'Piastowska','building_number'=>33,'postal_code'=>'17-783','city_id'=>305],
            ['street_name'=>'Polna','building_number'=>77,'postal_code'=>'12-641','city_id'=>305],
            ['street_name'=>'Wołodyjowskiego Michała','building_number'=>59,'postal_code'=>'46-242','city_id'=>88],
            ['street_name'=>'Niepodległości','building_number'=>48,'postal_code'=>'90-460','city_id'=>273],
            ['street_name'=>'Kolejowa','building_number'=>14,'postal_code'=>'28-923','city_id'=>180],
            ['street_name'=>'Białostocka','building_number'=>34,'postal_code'=>'79-910','city_id'=>230],
            ['street_name'=>'Małopolska','building_number'=>17,'postal_code'=>'69-486','city_id'=>168],
            ['street_name'=>'Łąkowa','building_number'=>9,'postal_code'=>'18-262','city_id'=>12],
            ['street_name'=>'Kościelna','building_number'=>29,'postal_code'=>'45-885','city_id'=>218],
            ['street_name'=>'Porzeczkowa','building_number'=>55,'postal_code'=>'05-789','city_id'=>266],
            ['street_name'=>'Sucha','building_number'=>22,'postal_code'=>'07-539','city_id'=>81],
            ['street_name'=>'Łużycka','building_number'=>5,'postal_code'=>'25-236','city_id'=>294],
            ['street_name'=>'Karpacka','building_number'=>96,'postal_code'=>'21-942','city_id'=>156],
            ['street_name'=>'Solidarności Al.','building_number'=>89,'postal_code'=>'98-731','city_id'=>278],
            ['street_name'=>'Łączna','building_number'=>29,'postal_code'=>'64-423','city_id'=>162],
            ['street_name'=>'Asnyka Adama','building_number'=>68,'postal_code'=>'39-260','city_id'=>303],
            ['street_name'=>'Morelowa','building_number'=>29,'postal_code'=>'01-102','city_id'=>296],
            ['street_name'=>'Jagodowa','building_number'=>10,'postal_code'=>'15-239','city_id'=>24],
            ['street_name'=>'Lawendowa','building_number'=>83,'postal_code'=>'95-371','city_id'=>252],
            ['street_name'=>'Księżycowa','building_number'=>8,'postal_code'=>'51-411','city_id'=>298],
            ['street_name'=>'Sikorskiego Władysława','building_number'=>56,'postal_code'=>'32-944','city_id'=>127],
            ['street_name'=>'Niska','building_number'=>57,'postal_code'=>'64-046','city_id'=>76],
            ['street_name'=>'Solidarności Al.','building_number'=>65,'postal_code'=>'99-318','city_id'=>132],
            ['street_name'=>'Żółkiewskiego Stanisława','building_number'=>95,'postal_code'=>'10-044','city_id'=>78],
            ['street_name'=>'Puszkina Aleksandra','building_number'=>74,'postal_code'=>'74-656','city_id'=>154],
            ['street_name'=>'Plater Emilii','building_number'=>34,'postal_code'=>'27-659','city_id'=>41],
            ['street_name'=>'Wybickiego Józefa','building_number'=>16,'postal_code'=>'98-355','city_id'=>62],
            ['street_name'=>'Wołodyjowskiego Michała','building_number'=>96,'postal_code'=>'06-715','city_id'=>126],
            ['street_name'=>'Radosna','building_number'=>45,'postal_code'=>'10-007','city_id'=>105],
            ['street_name'=>'Sikorskiego Władysława','building_number'=>83,'postal_code'=>'63-968','city_id'=>255],
            ['street_name'=>'Lotników','building_number'=>96,'postal_code'=>'47-175','city_id'=>80],
            ['street_name'=>'Żeromskiego Stefana','building_number'=>82,'postal_code'=>'66-475','city_id'=>262],
            ['street_name'=>'Głogowska','building_number'=>30,'postal_code'=>'98-919','city_id'=>97],
            ['street_name'=>'Pocztowa','building_number'=>66,'postal_code'=>'63-129','city_id'=>157],
            ['street_name'=>'Bema Józefa','building_number'=>89,'postal_code'=>'39-660','city_id'=>187],
            ['street_name'=>'Hallera Józefa','building_number'=>63,'postal_code'=>'73-337','city_id'=>244],
            ['street_name'=>'Sobieskiego Jana III','building_number'=>70,'postal_code'=>'30-885','city_id'=>236],
            ['street_name'=>'Złota','building_number'=>69,'postal_code'=>'81-112','city_id'=>67],
            ['street_name'=>'Curie-Skłodowskiej Marii','building_number'=>29,'postal_code'=>'59-918','city_id'=>68],
            ['street_name'=>'Kujawska','building_number'=>46,'postal_code'=>'18-712','city_id'=>238],
            ['street_name'=>'Bukowa','building_number'=>20,'postal_code'=>'50-491','city_id'=>245],
            ['street_name'=>'Nowowiejska','building_number'=>57,'postal_code'=>'81-605','city_id'=>9],
            ['street_name'=>'Krasińskiego Zygmunta','building_number'=>9,'postal_code'=>'33-735','city_id'=>14],
            ['street_name'=>'Modlińska','building_number'=>99,'postal_code'=>'10-202','city_id'=>106],
            ['street_name'=>'Wiosenna','building_number'=>85,'postal_code'=>'52-926','city_id'=>123],
            ['street_name'=>'Skośna','building_number'=>30,'postal_code'=>'47-452','city_id'=>65],
            ['street_name'=>'Solidarności Al.','building_number'=>45,'postal_code'=>'02-613','city_id'=>222],
            ['street_name'=>'Oświęcimska','building_number'=>20,'postal_code'=>'81-142','city_id'=>66],
            ['street_name'=>'Lipowa','building_number'=>87,'postal_code'=>'20-084','city_id'=>281],
            ['street_name'=>'Asnyka Adama','building_number'=>96,'postal_code'=>'85-876','city_id'=>241],
            ['street_name'=>'Lawendowa','building_number'=>36,'postal_code'=>'98-388','city_id'=>269],
            ['street_name'=>'Hallera Józefa','building_number'=>67,'postal_code'=>'57-115','city_id'=>1],
            ['street_name'=>'Hallera Józefa','building_number'=>10,'postal_code'=>'35-406','city_id'=>89],
            ['street_name'=>'Wileńska','building_number'=>7,'postal_code'=>'71-061','city_id'=>160],
            ['street_name'=>'Kasztanowa','building_number'=>18,'postal_code'=>'96-002','city_id'=>305],
            ['street_name'=>'Bema Józefa','building_number'=>64,'postal_code'=>'44-072','city_id'=>119],
            ['street_name'=>'Stalowa','building_number'=>45,'postal_code'=>'59-721','city_id'=>272],
            ['street_name'=>'Lipowa','building_number'=>46,'postal_code'=>'63-797','city_id'=>151],
            ['street_name'=>'Wesoła','building_number'=>62,'postal_code'=>'69-137','city_id'=>324]
        ]);
    }
}
