<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->insert([
            ['name' => 'Białogard', 'voivodeship_id' => 1],
            ['name' => 'Choszczno', 'voivodeship_id' => 1],
            ['name' => 'Drawsko Pomorskie', 'voivodeship_id' => 1],
            ['name' => 'Goleniów', 'voivodeship_id' => 1],
            ['name' => 'Gryfice', 'voivodeship_id' => 1],
            ['name' => 'Gryfino', 'voivodeship_id' => 1],
            ['name' => 'Kamień Pomorski', 'voivodeship_id' => 1],
            ['name' => 'Kołobrzeg', 'voivodeship_id' => 1],
            ['name' => 'Koszalin', 'voivodeship_id' => 1],
            ['name' => 'Łobez', 'voivodeship_id' => 1],
            ['name' => 'Myślibórz', 'voivodeship_id' => 1],
            ['name' => 'Police', 'voivodeship_id' => 1],
            ['name' => 'Pyrzyce', 'voivodeship_id' => 1],
            ['name' => 'Stargard', 'voivodeship_id' => 1],
            ['name' => 'Szczecin', 'voivodeship_id' => 1],
            ['name' => 'Szczecinek', 'voivodeship_id' => 1],
            ['name' => 'Świdnin', 'voivodeship_id' => 1],
            ['name' => 'Wałcz', 'voivodeship_id' => 1],
            ['name' => 'Bytów', 'voivodeship_id' => 2],
            ['name' => 'Chojnice', 'voivodeship_id' => 2],
            ['name' => 'Czułchów', 'voivodeship_id' => 2],
            ['name' => 'Gdańsk', 'voivodeship_id' => 2],
            ['name' => 'Gdynia', 'voivodeship_id' => 2],
            ['name' => 'Pruszcz Gdański', 'voivodeship_id' => 2],
            ['name' => 'Kartuzy', 'voivodeship_id' => 2],
            ['name' => 'Kościerzyna', 'voivodeship_id' => 2],
            ['name' => 'Kwidzyn', 'voivodeship_id' => 2],
            ['name' => 'Lębork', 'voivodeship_id' => 2],
            ['name' => 'Malbork', 'voivodeship_id' => 2],
            ['name' => 'Nowy Dwór Gdański', 'voivodeship_id' => 2],
            ['name' => 'Puck', 'voivodeship_id' => 2],
            ['name' => 'Słupsk', 'voivodeship_id' => 2],
            ['name' => 'Starogard Gdański', 'voivodeship_id' => 2],
            ['name' => 'Słupsk', 'voivodeship_id' => 2],
            ['name' => 'Tczew', 'voivodeship_id' => 2],
            ['name' => 'Wejherowo', 'voivodeship_id' => 2],
            ['name' => 'Bartoszyce', 'voivodeship_id' => 3],
            ['name' => 'Braniewo', 'voivodeship_id' => 3],
            ['name' => 'Działdowo', 'voivodeship_id' => 3],
            ['name' => 'Elbląg', 'voivodeship_id' => 3],
            ['name' => 'Ełk', 'voivodeship_id' => 3],
            ['name' => 'Giżycko', 'voivodeship_id' => 3],
            ['name' => 'Gołdap', 'voivodeship_id' => 3],
            ['name' => 'Iława', 'voivodeship_id' => 3],
            ['name' => 'Kętrzyn', 'voivodeship_id' => 3],
            ['name' => 'Lidzbark Warmiński', 'voivodeship_id' => 3],
            ['name' => 'Mrągowo', 'voivodeship_id' => 3],
            ['name' => 'Nidzica', 'voivodeship_id' => 3],
            ['name' => 'Nowe Miasto Lubawskie', 'voivodeship_id' => 3],
            ['name' => 'Olecko', 'voivodeship_id' => 3],
            ['name' => 'Olsztyn', 'voivodeship_id' => 3],
            ['name' => 'Ostróda', 'voivodeship_id' => 3],
            ['name' => 'Pisz', 'voivodeship_id' => 3],
            ['name' => 'Szczytno', 'voivodeship_id' => 3],
            ['name' => 'Węgorzewo', 'voivodeship_id' => 3],
            ['name' => 'Augustów', 'voivodeship_id' => 4],
            ['name' => 'Białystok', 'voivodeship_id' => 4],
            ['name' => 'Bielsk Podlaski', 'voivodeship_id' => 4],
            ['name' => 'Grajewo', 'voivodeship_id' => 4],
            ['name' => 'Hajnówka', 'voivodeship_id' => 4],
            ['name' => 'Kolno', 'voivodeship_id' => 4],
            ['name' => 'Łomża', 'voivodeship_id' => 4],
            ['name' => 'Mońki', 'voivodeship_id' => 4],
            ['name' => 'Sejny', 'voivodeship_id' => 4],
            ['name' => 'Siemiatycze', 'voivodeship_id' => 4],
            ['name' => 'Sokółka', 'voivodeship_id' => 4],
            ['name' => 'Suwałki', 'voivodeship_id' => 4],
            ['name' => 'Wysokie Mazowieckie', 'voivodeship_id' => 4],
            ['name' => 'Zambrów', 'voivodeship_id' => 4],
            ['name' => 'Gorzów Wielkopolski', 'voivodeship_id' => 5],
            ['name' => 'Krosno Odrzańskie', 'voivodeship_id' => 5],
            ['name' => 'Międzyrzecz', 'voivodeship_id' => 5],
            ['name' => 'Nowa Sól', 'voivodeship_id' => 5],
            ['name' => 'Słubice', 'voivodeship_id' => 5],
            ['name' => 'Strzelce Krajeńskie', 'voivodeship_id' => 5],
            ['name' => 'Sulęcin', 'voivodeship_id' => 5],
            ['name' => 'Świebodzin', 'voivodeship_id' => 5],
            ['name' => 'Wschowa', 'voivodeship_id' => 5],
            ['name' => 'Zielona Góra', 'voivodeship_id' => 5],
            ['name' => 'Żagań', 'voivodeship_id' => 5],
            ['name' => 'Żary', 'voivodeship_id' => 5],
            ['name' => 'Chodzież', 'voivodeship_id' => 6],
            ['name' => 'Czarnków', 'voivodeship_id' => 6],
            ['name' => 'Gniezno', 'voivodeship_id' => 6],
            ['name' => 'Gostyń', 'voivodeship_id' => 6],
            ['name' => 'Grodzisk Wielkopolski', 'voivodeship_id' => 6],
            ['name' => 'Jarocin', 'voivodeship_id' => 6],
            ['name' => 'Kalisz', 'voivodeship_id' => 6],
            ['name' => 'Kępno', 'voivodeship_id' => 6],
            ['name' => 'Koło', 'voivodeship_id' => 6],
            ['name' => 'Konin', 'voivodeship_id' => 6],
            ['name' => 'Kościan', 'voivodeship_id' => 6],
            ['name' => 'Krotoszyn', 'voivodeship_id' => 6],
            ['name' => 'Leszno', 'voivodeship_id' => 6],
            ['name' => 'Międzychód', 'voivodeship_id' => 6],
            ['name' => 'Nowy Tomyśl', 'voivodeship_id' => 6],
            ['name' => 'Oborniki', 'voivodeship_id' => 6],
            ['name' => 'Ostrów Wielkopolski', 'voivodeship_id' => 6],
            ['name' => 'Ostrzeszów', 'voivodeship_id' => 6],
            ['name' => 'Piła', 'voivodeship_id' => 6],
            ['name' => 'Pleszew', 'voivodeship_id' => 6],
            ['name' => 'Poznań', 'voivodeship_id' => 6],
            ['name' => 'Rawicz', 'voivodeship_id' => 6],
            ['name' => 'Słupca', 'voivodeship_id' => 6],
            ['name' => 'Szamotuły', 'voivodeship_id' => 6],
            ['name' => 'Środa Wielkopolska', 'voivodeship_id' => 6],
            ['name' => 'Śrem', 'voivodeship_id' => 6],
            ['name' => 'Turek', 'voivodeship_id' => 6],
            ['name' => 'Wągrowiec', 'voivodeship_id' => 6],
            ['name' => 'Wolsztyn', 'voivodeship_id' => 6],
            ['name' => 'Września', 'voivodeship_id' => 6],
            ['name' => 'Złotów', 'voivodeship_id' => 6],
            ['name' => 'Aleksandrów Kujawski', 'voivodeship_id' => 7],
            ['name' => 'Brodnica', 'voivodeship_id' => 7],
            ['name' => 'Bydgoszcz', 'voivodeship_id' => 7],
            ['name' => 'Chełmno', 'voivodeship_id' => 7],
            ['name' => 'Golub-Dobrzyń', 'voivodeship_id' => 7],
            ['name' => 'Grudziądz', 'voivodeship_id' => 7],
            ['name' => 'Inowrocław', 'voivodeship_id' => 7],
            ['name' => 'Lipno', 'voivodeship_id' => 7],
            ['name' => 'Mogilno', 'voivodeship_id' => 7],
            ['name' => 'Nakło nad Notecią', 'voivodeship_id' => 7],
            ['name' => 'Radziejów', 'voivodeship_id' => 7],
            ['name' => 'Rypin', 'voivodeship_id' => 7],
            ['name' => 'Sępólno Krajeńskie', 'voivodeship_id' => 7],
            ['name' => 'Świecie', 'voivodeship_id' => 7],
            ['name' => 'Toruń', 'voivodeship_id' => 7],
            ['name' => 'Tuchola', 'voivodeship_id' => 7],
            ['name' => 'Wąbrzeźno', 'voivodeship_id' => 7],
            ['name' => 'Włocławek', 'voivodeship_id' => 7],
            ['name' => 'Żnin', 'voivodeship_id' => 7],
            ['name' => 'Białobrzegi', 'voivodeship_id' => 8],
            ['name' => 'Ciechanów', 'voivodeship_id' => 8],
            ['name' => 'Garwolin', 'voivodeship_id' => 8],
            ['name' => 'Gostynin', 'voivodeship_id' => 8],
            ['name' => 'Grodzisk Mazowiecki', 'voivodeship_id' => 8],
            ['name' => 'Grójec', 'voivodeship_id' => 8],
            ['name' => 'Kozienice', 'voivodeship_id' => 8],
            ['name' => 'Legionowo', 'voivodeship_id' => 8],
            ['name' => 'Lipsko', 'voivodeship_id' => 8],
            ['name' => 'Łosice', 'voivodeship_id' => 8],
            ['name' => 'Maków Mazowiecki', 'voivodeship_id' => 8],
            ['name' => 'Mińsk Mazowiecki', 'voivodeship_id' => 8],
            ['name' => 'Mława', 'voivodeship_id' => 8],
            ['name' => 'Nowy Dwór Mazowiecki', 'voivodeship_id' => 8],
            ['name' => 'Ostrołęka', 'voivodeship_id' => 8],
            ['name' => 'Ostrów Mazowiecka', 'voivodeship_id' => 8],
            ['name' => 'Otwock', 'voivodeship_id' => 8],
            ['name' => 'Piaseczno', 'voivodeship_id' => 8],
            ['name' => 'Płock', 'voivodeship_id' => 8],
            ['name' => 'Płońsk', 'voivodeship_id' => 8],
            ['name' => 'Pruszków', 'voivodeship_id' => 8],
            ['name' => 'Przasnysz', 'voivodeship_id' => 8],
            ['name' => 'Przysucha', 'voivodeship_id' => 8],
            ['name' => 'Pułtusk', 'voivodeship_id' => 8],
            ['name' => 'Radom', 'voivodeship_id' => 8],
            ['name' => 'Siedlce', 'voivodeship_id' => 8],
            ['name' => 'Sierpc', 'voivodeship_id' => 8],
            ['name' => 'Sochaczew', 'voivodeship_id' => 8],
            ['name' => 'Sokołów Podlaski', 'voivodeship_id' => 8],
            ['name' => 'Szydłowiec', 'voivodeship_id' => 8],
            ['name' => 'Ożarów Mazowiecki', 'voivodeship_id' => 8],
            ['name' => 'Warszawa', 'voivodeship_id' => 8],
            ['name' => 'Węgrów', 'voivodeship_id' => 8],
            ['name' => 'Wołomin', 'voivodeship_id' => 8],
            ['name' => 'Wyszków', 'voivodeship_id' => 8],
            ['name' => 'Zwoleń', 'voivodeship_id' => 8],
            ['name' => 'Żuromin', 'voivodeship_id' => 8],
            ['name' => 'Żyrardów', 'voivodeship_id' => 8],
            ['name' => 'Bolesławiec', 'voivodeship_id' => 9],
            ['name' => 'Dzierżoniów', 'voivodeship_id' => 9],
            ['name' => 'Góra', 'voivodeship_id' => 9],
            ['name' => 'Jawor', 'voivodeship_id' => 9],
            ['name' => 'Głogów', 'voivodeship_id' => 9],
            ['name' => 'Jelenia Góra', 'voivodeship_id' => 9],
            ['name' => 'Kamienna Góra', 'voivodeship_id' => 9],
            ['name' => 'Kłodzko', 'voivodeship_id' => 9],
            ['name' => 'Legnica', 'voivodeship_id' => 9],
            ['name' => 'Lubań', 'voivodeship_id' => 9],
            ['name' => 'Lubin', 'voivodeship_id' => 9],
            ['name' => 'Lwówek Śląski', 'voivodeship_id' => 9],
            ['name' => 'Milicz', 'voivodeship_id' => 9],
            ['name' => 'Oleśnica', 'voivodeship_id' => 9],
            ['name' => 'Oława', 'voivodeship_id' => 9],
            ['name' => 'Polkowice', 'voivodeship_id' => 9],
            ['name' => 'Strzelin', 'voivodeship_id' => 9],
            ['name' => 'Środa Śląska', 'voivodeship_id' => 9],
            ['name' => 'Świdnica', 'voivodeship_id' => 9],
            ['name' => 'Trzebnica', 'voivodeship_id' => 9],
            ['name' => 'Wałbrzych', 'voivodeship_id' => 9],
            ['name' => 'Wołów', 'voivodeship_id' => 9],
            ['name' => 'Wrocław', 'voivodeship_id' => 9],
            ['name' => 'Ząbkowice Sląskie', 'voivodeship_id' => 9],
            ['name' => 'Zgorzelec', 'voivodeship_id' => 9],
            ['name' => 'Złotoryja', 'voivodeship_id' => 9],
            ['name' => 'Bełchatów', 'voivodeship_id' => 10],
            ['name' => 'Brzeziny', 'voivodeship_id' => 10],
            ['name' => 'Kutno', 'voivodeship_id' => 10],
            ['name' => 'Łask', 'voivodeship_id' => 10],
            ['name' => 'Łęczyca', 'voivodeship_id' => 10],
            ['name' => 'Łowicz', 'voivodeship_id' => 10],
            ['name' => 'Łódź', 'voivodeship_id' => 10],
            ['name' => 'Opoczno', 'voivodeship_id' => 10],
            ['name' => 'Pabianice', 'voivodeship_id' => 10],
            ['name' => 'Pajęczno', 'voivodeship_id' => 10],
            ['name' => 'Piotrków Trybunalski', 'voivodeship_id' => 10],
            ['name' => 'Poddębice', 'voivodeship_id' => 10],
            ['name' => 'Radomsko', 'voivodeship_id' => 10],
            ['name' => 'Rawa Mazowiecka', 'voivodeship_id' => 10],
            ['name' => 'Sieradz', 'voivodeship_id' => 10],
            ['name' => 'Skierniewice', 'voivodeship_id' => 10],
            ['name' => 'Tomaszów Mazowiecki', 'voivodeship_id' => 10],
            ['name' => 'Wieluń', 'voivodeship_id' => 10],
            ['name' => 'Wieruszów', 'voivodeship_id' => 10],
            ['name' => 'Zduńska Wola', 'voivodeship_id' => 10],
            ['name' => 'Zgierz', 'voivodeship_id' => 10],
            ['name' => 'Busko-Zdrój', 'voivodeship_id' => 11],
            ['name' => 'Jędrzejów', 'voivodeship_id' => 11],
            ['name' => 'Kazimerza Wielka', 'voivodeship_id' => 11],
            ['name' => 'Kielce', 'voivodeship_id' => 11],
            ['name' => 'Końskie', 'voivodeship_id' => 11],
            ['name' => 'Opatów', 'voivodeship_id' => 11],
            ['name' => 'Ostrowiec Świętokrzyski', 'voivodeship_id' => 11],
            ['name' => 'Pińczów', 'voivodeship_id' => 11],
            ['name' => 'Sandomierz', 'voivodeship_id' => 11],
            ['name' => 'Skarżysko-Kamienna', 'voivodeship_id' => 11],
            ['name' => 'Staszów', 'voivodeship_id' => 11],
            ['name' => 'Włoszczowa', 'voivodeship_id' => 11],
            ['name' => 'Biała Podlaska', 'voivodeship_id' => 12],
            ['name' => 'Biłgoraj', 'voivodeship_id' => 12],
            ['name' => 'Chełm', 'voivodeship_id' => 12],
            ['name' => 'Hrubieszów', 'voivodeship_id' => 12],
            ['name' => 'Janów Lubelski', 'voivodeship_id' => 12],
            ['name' => 'Krasnystaw', 'voivodeship_id' => 12],
            ['name' => 'Kraśnik', 'voivodeship_id' => 12],
            ['name' => 'Lubartów', 'voivodeship_id' => 12],
            ['name' => 'Lublin', 'voivodeship_id' => 12],
            ['name' => 'Łęczna', 'voivodeship_id' => 12],
            ['name' => 'Łuków', 'voivodeship_id' => 12],
            ['name' => 'Opole Lubelskie', 'voivodeship_id' => 12],
            ['name' => 'Parczew', 'voivodeship_id' => 12],
            ['name' => 'Puławy', 'voivodeship_id' => 12],
            ['name' => 'Radzyń Podlaski', 'voivodeship_id' => 12],
            ['name' => 'Ryki', 'voivodeship_id' => 12],
            ['name' => 'Świdnik', 'voivodeship_id' => 12],
            ['name' => 'Włodawa', 'voivodeship_id' => 12],
            ['name' => 'Zamość', 'voivodeship_id' => 12],
            ['name' => 'Brzeg', 'voivodeship_id' => 13],
            ['name' => 'Głubczyce', 'voivodeship_id' => 13],
            ['name' => 'Kędzierzyn-Koźle', 'voivodeship_id' => 13],
            ['name' => 'Kluczbork', 'voivodeship_id' => 13],
            ['name' => 'Krapkowice', 'voivodeship_id' => 13],
            ['name' => 'Namysłów', 'voivodeship_id' => 13],
            ['name' => 'Nysa', 'voivodeship_id' => 13],
            ['name' => 'Olesno', 'voivodeship_id' => 13],
            ['name' => 'Opole', 'voivodeship_id' => 13],
            ['name' => 'Prudnik', 'voivodeship_id' => 13],
            ['name' => 'Strzelce Opolskie', 'voivodeship_id' => 13],
            ['name' => 'Będzin', 'voivodeship_id' => 14],
            ['name' => 'Bielsko-Biała', 'voivodeship_id' => 14],
            ['name' => 'Bieruń', 'voivodeship_id' => 14],
            ['name' => 'Cieszyn', 'voivodeship_id' => 14],
            ['name' => 'Częstochowa', 'voivodeship_id' => 14],
            ['name' => 'Gliwice', 'voivodeship_id' => 14],
            ['name' => 'Kłobuck', 'voivodeship_id' => 14],
            ['name' => 'Lubliniec', 'voivodeship_id' => 14],
            ['name' => 'Mikołów', 'voivodeship_id' => 14],
            ['name' => 'Myszków', 'voivodeship_id' => 14],
            ['name' => 'Pszczyna', 'voivodeship_id' => 14],
            ['name' => 'Racibórz', 'voivodeship_id' => 14],
            ['name' => 'Rybnik', 'voivodeship_id' => 14],
            ['name' => 'Tarnowskie Góry', 'voivodeship_id' => 14],
            ['name' => 'Wodzisław Śląski', 'voivodeship_id' => 14],
            ['name' => 'Zawiercie', 'voivodeship_id' => 14],
            ['name' => 'Żywiec', 'voivodeship_id' => 14],
            ['name' => 'Katowice', 'voivodeship_id' => 14],
            ['name' => 'Bytom', 'voivodeship_id' => 14],
            ['name' => 'Chorzów', 'voivodeship_id' => 14],
            ['name' => 'Dąbrowa Górnicza', 'voivodeship_id' => 14],
            ['name' => 'Jastrzębie-Zdrój', 'voivodeship_id' => 14],
            ['name' => 'Jaworzno', 'voivodeship_id' => 14],
            ['name' => 'Mysłowice', 'voivodeship_id' => 14],
            ['name' => 'Piekary Śląskie', 'voivodeship_id' => 14],
            ['name' => 'Ruda Śląska', 'voivodeship_id' => 14],
            ['name' => 'Siemianowice Śląskie', 'voivodeship_id' => 14],
            ['name' => 'Sosnowiec', 'voivodeship_id' => 14],
            ['name' => 'Świętochłowce', 'voivodeship_id' => 14],
            ['name' => 'Tychy', 'voivodeship_id' => 14],
            ['name' => 'Zabrze', 'voivodeship_id' => 14],
            ['name' => 'Żory', 'voivodeship_id' => 14],
            ['name' => 'Bochnia', 'voivodeship_id' => 15],
            ['name' => 'Brzesko', 'voivodeship_id' => 15],
            ['name' => 'Chrzanów', 'voivodeship_id' => 15],
            ['name' => 'Dąbrowa Tarnowska', 'voivodeship_id' => 15],
            ['name' => 'Gorlice', 'voivodeship_id' => 15],
            ['name' => 'Kraków', 'voivodeship_id' => 15],
            ['name' => 'Limanowa', 'voivodeship_id' => 15],
            ['name' => 'Miechów', 'voivodeship_id' => 15],
            ['name' => 'Myślenice', 'voivodeship_id' => 15],
            ['name' => 'Nowy Sącz', 'voivodeship_id' => 15],
            ['name' => 'Nowy Targ', 'voivodeship_id' => 15],
            ['name' => 'Olkusz', 'voivodeship_id' => 15],
            ['name' => 'Ośiwęcim', 'voivodeship_id' => 15],
            ['name' => 'Proszkowice', 'voivodeship_id' => 15],
            ['name' => 'Sucha Beskidzka', 'voivodeship_id' => 15],
            ['name' => 'Tarnów', 'voivodeship_id' => 15],
            ['name' => 'Zakopane', 'voivodeship_id' => 15],
            ['name' => 'Wadowice', 'voivodeship_id' => 15],
            ['name' => 'Wieliczka', 'voivodeship_id' => 15],
            ['name' => 'Ustrzyki Dolne', 'voivodeship_id' => 16],
            ['name' => 'Brzozów', 'voivodeship_id' => 16],
            ['name' => 'Dębica', 'voivodeship_id' => 16],
            ['name' => 'Jarosław', 'voivodeship_id' => 16],
            ['name' => 'Jasło', 'voivodeship_id' => 16],
            ['name' => 'Kolbuszowa', 'voivodeship_id' => 16],
            ['name' => 'Krosno', 'voivodeship_id' => 16],
            ['name' => 'Lesko', 'voivodeship_id' => 16],
            ['name' => 'Leżajsk', 'voivodeship_id' => 16],
            ['name' => 'Lubaczów', 'voivodeship_id' => 16],
            ['name' => 'Łańcut', 'voivodeship_id' => 16],
            ['name' => 'Mielec', 'voivodeship_id' => 16],
            ['name' => 'Nisko', 'voivodeship_id' => 16],
            ['name' => 'Przemyśl', 'voivodeship_id' => 16],
            ['name' => 'Przeworsk', 'voivodeship_id' => 16],
            ['name' => 'Ropczyce', 'voivodeship_id' => 16],
            ['name' => 'Rzeszów', 'voivodeship_id' => 16],
            ['name' => 'Sanok', 'voivodeship_id' => 16],
            ['name' => 'Stalowa Wola', 'voivodeship_id' => 16],
            ['name' => 'Strzyżów', 'voivodeship_id' => 16],
            ['name' => 'Tarnobrzeg', 'voivodeship_id' => 16],
        ]);
    }
}
